import axios from 'axios';

const rootURL = 'http://localhost:8000';
const productAPI = `${rootURL}/api/v1/product`;

export const fetchProduct = async () => {
  try {
    const { data } = await axios.get(productAPI);
    return data;
  } catch (error) {
    return (
      error?.response.data || {
        status: 'error',
        message: error.message, //gets error generated by the system
      }
    );
  }
};
